-- 코드를 입력하세요
SELECT distinct r1.USER_ID USER_ID, r1.PRODUCT_ID PRODUCT_ID
FROM ONLINE_SALE r1, ONLINE_SALE r2
WHERE r1.USER_ID = r2.USER_ID
    and r1.PRODUCT_ID = r2.PRODUCT_ID
    and r1.ONLINE_SALE_ID <> r2.ONLINE_SALE_ID 
ORDER BY r1.USER_ID, r1.PRODUCT_ID desc