System.Console.WriteLine(@"     /~\");
System.Console.WriteLine(@"    ( oo|");
System.Console.WriteLine(@"    _\=/_");
System.Console.WriteLine(@"   /  _  \");
System.Console.WriteLine(@"  //|/.\|\\");
System.Console.WriteLine(@" ||  \ /  ||");
System.Console.WriteLine(@"============");
System.Console.WriteLine(@"|          |");
System.Console.WriteLine(@"|          |");
System.Console.WriteLine(@"|          |");
