-- 코드를 입력하세요
SELECT YEAR, MONTH, GENDER, COUNT(distinct USER_ID) USERS
FROM (
    SELECT ONLINE_SALE.USER_ID USER_ID, YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, GENDER
    FROM ONLINE_SALE, USER_INFO
    WHERE ONLINE_SALE.USER_ID = USER_INFO.USER_ID
        and GENDER is not null
    ) T
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER